### ISSUE TITLE
a little question about the paper

### ISSUE THREAD

**Issue by NHZlX** [zongyuange/MixDCNN#1]
hello,  i am reading your paper . now i know about process of the test  with regard to the mixDCNN, but i can not find the train process in the paper.  or maybe i was too careless , so can u give me some advice.

**Comment by zongyuange** [comment]
Hi NHZIX, thanks for your interest. Yes, you are right, current version only includes testing function, the training function is not posted here because it involves pre-clustering and feature fusion as described in the paper. 
However, we are trying hard to make the clustering code ready and release soon.
Meanwhile, the easiest way to re-train the model yourself is either fine-tuning provided models on a new task or combine 4 feature caffemodels yourself (http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/net_surgery.ipynb) and run the script.
