### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ouceduxzk** [zongyuange/MixDCNN#2]
1. the code does not compile with cudnn v4
2. after set cudnn 0,  got following error : 
   examples/cifar10/convert_cifar_data.cpp:18:29: fatal error: caffe/util/db.hpp: No such file or directory
   #include "caffe/util/db.hpp"

Any idea how to fix this ?

**Comment by zongyuange** [comment]
Hello. Thanks for your question. The Caffe version being used for this project is a 2014-9 version, which might result in compatible issue with latest cudnn. I suggest use an older version of cudnn.

**Comment by ouceduxzk** [comment]
Thanks, besides that, how do you choose the number , k ?  and do you have any follow up work on fine-grained classification?

**Comment by zongyuange** [comment]
Hi Zuck, thanks for your interest of my work. I am currently working on medical image problems. But there will be some work in my pipeline for fine-grained classification. Keep an eye on my website. 

For the number of clusters K, I simply try 2,4,6 and choose the one with the best performance. 6 is the maximum number I tried because of the GPU memory limitation. (12G on K40)
